name: mobile_BTM
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #dependencies
  easy_localization: ^2.3.2
  flutter_modular: ^1.2.5+1
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  #dependencies end

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #dev dependencies
  mobx_codegen: ^1.1.0+1
  build_runner:
  #dev dependencies end

flutter:
  uses-material-design: true

  assets:
    - lang/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 